// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.banco.domain;

import com.banco.domain.Cliente;
import com.banco.domain.ClienteDataOnDemand;
import com.banco.domain.ClienteIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClienteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClienteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClienteIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ClienteIntegrationTest: @Transactional;
    
    @Autowired
    ClienteDataOnDemand ClienteIntegrationTest.dod;
    
    @Test
    public void ClienteIntegrationTest.testCountClientes() {
        Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", dod.getRandomCliente());
        long count = Cliente.countClientes();
        Assert.assertTrue("Counter for 'Cliente' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClienteIntegrationTest.testFindCliente() {
        Cliente obj = dod.getRandomCliente();
        Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cliente' failed to provide an identifier", id);
        obj = Cliente.findCliente(id);
        Assert.assertNotNull("Find method for 'Cliente' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Cliente' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClienteIntegrationTest.testFindAllClientes() {
        Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", dod.getRandomCliente());
        long count = Cliente.countClientes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Cliente', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Cliente> result = Cliente.findAllClientes();
        Assert.assertNotNull("Find all method for 'Cliente' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Cliente' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClienteIntegrationTest.testFindClienteEntries() {
        Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", dod.getRandomCliente());
        long count = Cliente.countClientes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Cliente> result = Cliente.findClienteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Cliente' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Cliente' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClienteIntegrationTest.testFlush() {
        Cliente obj = dod.getRandomCliente();
        Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cliente' failed to provide an identifier", id);
        obj = Cliente.findCliente(id);
        Assert.assertNotNull("Find method for 'Cliente' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCliente(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Cliente' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClienteIntegrationTest.testMergeUpdate() {
        Cliente obj = dod.getRandomCliente();
        Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cliente' failed to provide an identifier", id);
        obj = Cliente.findCliente(id);
        boolean modified =  dod.modifyCliente(obj);
        Integer currentVersion = obj.getVersion();
        Cliente merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Cliente' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClienteIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", dod.getRandomCliente());
        Cliente obj = dod.getNewTransientCliente(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Cliente' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Cliente' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Cliente' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClienteIntegrationTest.testRemove() {
        Cliente obj = dod.getRandomCliente();
        Assert.assertNotNull("Data on demand for 'Cliente' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Cliente' failed to provide an identifier", id);
        obj = Cliente.findCliente(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Cliente' with identifier '" + id + "'", Cliente.findCliente(id));
    }
    
}
