// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.banco.domain;

import com.banco.domain.Cliente;
import com.banco.domain.ClienteDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ClienteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClienteDataOnDemand: @Component;
    
    private Random ClienteDataOnDemand.rnd = new SecureRandom();
    
    private List<Cliente> ClienteDataOnDemand.data;
    
    public Cliente ClienteDataOnDemand.getNewTransientCliente(int index) {
        Cliente obj = new Cliente();
        setDireccion(obj, index);
        setNombre(obj, index);
        setPassword(obj, index);
        setTelefone(obj, index);
        setUsuario(obj, index);
        return obj;
    }
    
    public void ClienteDataOnDemand.setDireccion(Cliente obj, int index) {
        String direccion = "direccion_" + index;
        if (direccion.length() > 50) {
            direccion = direccion.substring(0, 50);
        }
        obj.setDireccion(direccion);
    }
    
    public void ClienteDataOnDemand.setNombre(Cliente obj, int index) {
        String nombre = "nombre_" + index;
        if (nombre.length() > 30) {
            nombre = nombre.substring(0, 30);
        }
        obj.setNombre(nombre);
    }
    
    public void ClienteDataOnDemand.setPassword(Cliente obj, int index) {
        String password = "password_" + index;
        if (password.length() > 70) {
            password = password.substring(0, 70);
        }
        obj.setPassword(password);
    }
    
    public void ClienteDataOnDemand.setTelefone(Cliente obj, int index) {
        String telefone = "telefone_" + index;
        obj.setTelefone(telefone);
    }
    
    public void ClienteDataOnDemand.setUsuario(Cliente obj, int index) {
        String usuario = "usuario_" + index;
        if (usuario.length() > 70) {
            usuario = usuario.substring(0, 70);
        }
        obj.setUsuario(usuario);
    }
    
    public Cliente ClienteDataOnDemand.getSpecificCliente(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Cliente obj = data.get(index);
        Long id = obj.getId();
        return Cliente.findCliente(id);
    }
    
    public Cliente ClienteDataOnDemand.getRandomCliente() {
        init();
        Cliente obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Cliente.findCliente(id);
    }
    
    public boolean ClienteDataOnDemand.modifyCliente(Cliente obj) {
        return false;
    }
    
    public void ClienteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Cliente.findClienteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Cliente' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Cliente>();
        for (int i = 0; i < 10; i++) {
            Cliente obj = getNewTransientCliente(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
