// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.banco.domain;

import com.banco.domain.CuentaDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CuentaDataOnDemand_Roo_Configurable {
    
    declare @type: CuentaDataOnDemand: @Configurable;
    
}
