// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.banco.domain;

import com.banco.domain.ClienteDataOnDemand;
import com.banco.domain.Cuenta;
import com.banco.domain.CuentaDataOnDemand;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CuentaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CuentaDataOnDemand: @Component;
    
    private Random CuentaDataOnDemand.rnd = new SecureRandom();
    
    private List<Cuenta> CuentaDataOnDemand.data;
    
    @Autowired
    ClienteDataOnDemand CuentaDataOnDemand.clienteDataOnDemand;
    
    public Cuenta CuentaDataOnDemand.getNewTransientCuenta(int index) {
        Cuenta obj = new Cuenta();
        setNumero(obj, index);
        setSaldo(obj, index);
        return obj;
    }
    
    public void CuentaDataOnDemand.setNumero(Cuenta obj, int index) {
        String numero = "numero_" + index;
        obj.setNumero(numero);
    }
    
    public void CuentaDataOnDemand.setSaldo(Cuenta obj, int index) {
        BigDecimal saldo = BigDecimal.valueOf(index);
        obj.setSaldo(saldo);
    }
    
    public Cuenta CuentaDataOnDemand.getSpecificCuenta(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Cuenta obj = data.get(index);
        Long id = obj.getId();
        return Cuenta.findCuenta(id);
    }
    
    public Cuenta CuentaDataOnDemand.getRandomCuenta() {
        init();
        Cuenta obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Cuenta.findCuenta(id);
    }
    
    public boolean CuentaDataOnDemand.modifyCuenta(Cuenta obj) {
        return false;
    }
    
    public void CuentaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Cuenta.findCuentaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Cuenta' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Cuenta>();
        for (int i = 0; i < 10; i++) {
            Cuenta obj = getNewTransientCuenta(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
