// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.banco.domain;

import com.banco.domain.CuentaDataOnDemand;
import com.banco.domain.Movimiento;
import com.banco.domain.MovimientoDataOnDemand;
import com.banco.reference.TipoMovimiento;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MovimientoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MovimientoDataOnDemand: @Component;
    
    private Random MovimientoDataOnDemand.rnd = new SecureRandom();
    
    private List<Movimiento> MovimientoDataOnDemand.data;
    
    @Autowired
    CuentaDataOnDemand MovimientoDataOnDemand.cuentaDataOnDemand;
    
    public Movimiento MovimientoDataOnDemand.getNewTransientMovimiento(int index) {
        Movimiento obj = new Movimiento();
        setFecha(obj, index);
        setTipo(obj, index);
        setValor(obj, index);
        return obj;
    }
    
    public void MovimientoDataOnDemand.setFecha(Movimiento obj, int index) {
        Date fecha = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFecha(fecha);
    }
    
    public void MovimientoDataOnDemand.setTipo(Movimiento obj, int index) {
        TipoMovimiento tipo = TipoMovimiento.class.getEnumConstants()[0];
        obj.setTipo(tipo);
    }
    
    public void MovimientoDataOnDemand.setValor(Movimiento obj, int index) {
        BigDecimal valor = BigDecimal.valueOf(index);
        obj.setValor(valor);
    }
    
    public Movimiento MovimientoDataOnDemand.getSpecificMovimiento(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Movimiento obj = data.get(index);
        Long id = obj.getId();
        return Movimiento.findMovimiento(id);
    }
    
    public Movimiento MovimientoDataOnDemand.getRandomMovimiento() {
        init();
        Movimiento obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Movimiento.findMovimiento(id);
    }
    
    public boolean MovimientoDataOnDemand.modifyMovimiento(Movimiento obj) {
        return false;
    }
    
    public void MovimientoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Movimiento.findMovimientoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Movimiento' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Movimiento>();
        for (int i = 0; i < 10; i++) {
            Movimiento obj = getNewTransientMovimiento(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
