// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.banco.domain;

import com.banco.domain.Movimiento;
import com.banco.domain.MovimientoDataOnDemand;
import com.banco.domain.MovimientoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MovimientoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MovimientoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MovimientoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MovimientoIntegrationTest: @Transactional;
    
    @Autowired
    MovimientoDataOnDemand MovimientoIntegrationTest.dod;
    
    @Test
    public void MovimientoIntegrationTest.testCountMovimientoes() {
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to initialize correctly", dod.getRandomMovimiento());
        long count = Movimiento.countMovimientoes();
        Assert.assertTrue("Counter for 'Movimiento' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MovimientoIntegrationTest.testFindMovimiento() {
        Movimiento obj = dod.getRandomMovimiento();
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to provide an identifier", id);
        obj = Movimiento.findMovimiento(id);
        Assert.assertNotNull("Find method for 'Movimiento' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Movimiento' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MovimientoIntegrationTest.testFindAllMovimientoes() {
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to initialize correctly", dod.getRandomMovimiento());
        long count = Movimiento.countMovimientoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Movimiento', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Movimiento> result = Movimiento.findAllMovimientoes();
        Assert.assertNotNull("Find all method for 'Movimiento' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Movimiento' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MovimientoIntegrationTest.testFindMovimientoEntries() {
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to initialize correctly", dod.getRandomMovimiento());
        long count = Movimiento.countMovimientoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Movimiento> result = Movimiento.findMovimientoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Movimiento' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Movimiento' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MovimientoIntegrationTest.testFlush() {
        Movimiento obj = dod.getRandomMovimiento();
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to provide an identifier", id);
        obj = Movimiento.findMovimiento(id);
        Assert.assertNotNull("Find method for 'Movimiento' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMovimiento(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Movimiento' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MovimientoIntegrationTest.testMergeUpdate() {
        Movimiento obj = dod.getRandomMovimiento();
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to provide an identifier", id);
        obj = Movimiento.findMovimiento(id);
        boolean modified =  dod.modifyMovimiento(obj);
        Integer currentVersion = obj.getVersion();
        Movimiento merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Movimiento' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MovimientoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to initialize correctly", dod.getRandomMovimiento());
        Movimiento obj = dod.getNewTransientMovimiento(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Movimiento' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Movimiento' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MovimientoIntegrationTest.testRemove() {
        Movimiento obj = dod.getRandomMovimiento();
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Movimiento' failed to provide an identifier", id);
        obj = Movimiento.findMovimiento(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Movimiento' with identifier '" + id + "'", Movimiento.findMovimiento(id));
    }
    
}
