// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.banco.domain;

import com.banco.domain.UsuarioRol;
import com.banco.domain.UsuarioRolDataOnDemand;
import com.banco.domain.UsuarioRolIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsuarioRolIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsuarioRolIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsuarioRolIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UsuarioRolIntegrationTest: @Transactional;
    
    @Autowired
    UsuarioRolDataOnDemand UsuarioRolIntegrationTest.dod;
    
    @Test
    public void UsuarioRolIntegrationTest.testCountUsuarioRols() {
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to initialize correctly", dod.getRandomUsuarioRol());
        long count = UsuarioRol.countUsuarioRols();
        Assert.assertTrue("Counter for 'UsuarioRol' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsuarioRolIntegrationTest.testFindUsuarioRol() {
        UsuarioRol obj = dod.getRandomUsuarioRol();
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to provide an identifier", id);
        obj = UsuarioRol.findUsuarioRol(id);
        Assert.assertNotNull("Find method for 'UsuarioRol' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UsuarioRol' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsuarioRolIntegrationTest.testFindAllUsuarioRols() {
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to initialize correctly", dod.getRandomUsuarioRol());
        long count = UsuarioRol.countUsuarioRols();
        Assert.assertTrue("Too expensive to perform a find all test for 'UsuarioRol', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UsuarioRol> result = UsuarioRol.findAllUsuarioRols();
        Assert.assertNotNull("Find all method for 'UsuarioRol' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UsuarioRol' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsuarioRolIntegrationTest.testFindUsuarioRolEntries() {
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to initialize correctly", dod.getRandomUsuarioRol());
        long count = UsuarioRol.countUsuarioRols();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UsuarioRol> result = UsuarioRol.findUsuarioRolEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UsuarioRol' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UsuarioRol' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UsuarioRolIntegrationTest.testFlush() {
        UsuarioRol obj = dod.getRandomUsuarioRol();
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to provide an identifier", id);
        obj = UsuarioRol.findUsuarioRol(id);
        Assert.assertNotNull("Find method for 'UsuarioRol' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUsuarioRol(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UsuarioRol' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsuarioRolIntegrationTest.testMergeUpdate() {
        UsuarioRol obj = dod.getRandomUsuarioRol();
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to provide an identifier", id);
        obj = UsuarioRol.findUsuarioRol(id);
        boolean modified =  dod.modifyUsuarioRol(obj);
        Integer currentVersion = obj.getVersion();
        UsuarioRol merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UsuarioRol' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsuarioRolIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to initialize correctly", dod.getRandomUsuarioRol());
        UsuarioRol obj = dod.getNewTransientUsuarioRol(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UsuarioRol' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UsuarioRol' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UsuarioRolIntegrationTest.testRemove() {
        UsuarioRol obj = dod.getRandomUsuarioRol();
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsuarioRol' failed to provide an identifier", id);
        obj = UsuarioRol.findUsuarioRol(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UsuarioRol' with identifier '" + id + "'", UsuarioRol.findUsuarioRol(id));
    }
    
}
